"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

NAME = 'ARAN'
VERSION = 0.51
APP = ['src/ARAN.py']
DATA_FILES = [('cl',['src/cl/kxky.cl']),('ini',['src/ini/config.ini'])]
OPTIONS = {'argv_emulation': True, 
				 'packages':['h5py','pyopencl','PyQt4'],
				 'includes':['packaging', 'packaging.version', 'packaging.specifiers', 'packaging.requirements','_cffi_backend','ConfigParser.SafeConfigParser'],
				 'iconfile': 'media/aran.icns'
   		  }

setup(
	name=NAME,
	version=VERSION,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
