# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui/Tools_ROIWidget2.ui'
#
# Created: Wed May 18 16:16:08 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Tools_ROIWidget(object):
    def setupUi(self, Tools_ROIWidget):
        Tools_ROIWidget.setObjectName("Tools_ROIWidget")
        Tools_ROIWidget.resize(283, 209)
        Tools_ROIWidget.setBaseSize(QtCore.QSize(283, 209))
        self.gridLayout = QtGui.QGridLayout(Tools_ROIWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(Tools_ROIWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horAddILROIBtn = QtGui.QPushButton(self.groupBox)
        self.horAddILROIBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horAddILROIBtn.setObjectName("horAddILROIBtn")
        self.verticalLayout_2.addWidget(self.horAddILROIBtn)
        self.verAddILROIBtn = QtGui.QPushButton(self.groupBox)
        self.verAddILROIBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verAddILROIBtn.setObjectName("verAddILROIBtn")
        self.verticalLayout_2.addWidget(self.verAddILROIBtn)
        self.addBoxROIBtn = QtGui.QPushButton(self.groupBox)
        self.addBoxROIBtn.setObjectName("addBoxROIBtn")
        self.verticalLayout_2.addWidget(self.addBoxROIBtn)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.anlgeROILbl = QtGui.QLabel(self.groupBox)
        self.anlgeROILbl.setObjectName("anlgeROILbl")
        self.horizontalLayout_2.addWidget(self.anlgeROILbl)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.screenAngleROICheckBox = QtGui.QCheckBox(self.groupBox)
        self.screenAngleROICheckBox.setEnabled(False)
        self.screenAngleROICheckBox.setObjectName("screenAngleROICheckBox")
        self.verticalLayout.addWidget(self.screenAngleROICheckBox)
        self.resetROIBtn = QtGui.QPushButton(self.groupBox)
        self.resetROIBtn.setEnabled(False)
        self.resetROIBtn.setObjectName("resetROIBtn")
        self.verticalLayout.addWidget(self.resetROIBtn)
        self.removeROIBtn = QtGui.QPushButton(self.groupBox)
        self.removeROIBtn.setEnabled(False)
        self.removeROIBtn.setObjectName("removeROIBtn")
        self.verticalLayout.addWidget(self.removeROIBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)

        self.retranslateUi(Tools_ROIWidget)
        QtCore.QMetaObject.connectSlotsByName(Tools_ROIWidget)

    def retranslateUi(self, Tools_ROIWidget):
        Tools_ROIWidget.setWindowTitle(QtGui.QApplication.translate("Tools_ROIWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Tools_ROIWidget", "Region of interest", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Add:", None, QtGui.QApplication.UnicodeUTF8))
        self.horAddILROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Hor line", None, QtGui.QApplication.UnicodeUTF8))
        self.verAddILROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Ver line", None, QtGui.QApplication.UnicodeUTF8))
        self.addBoxROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Box", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Selected:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Angle:", None, QtGui.QApplication.UnicodeUTF8))
        self.anlgeROILbl.setText(QtGui.QApplication.translate("Tools_ROIWidget", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Tools_ROIWidget", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.screenAngleROICheckBox.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Detector angles", None, QtGui.QApplication.UnicodeUTF8))
        self.resetROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.removeROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Remove", None, QtGui.QApplication.UnicodeUTF8))

