# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view/ui/Tools_ROIWidget.ui'
#
# Created: Fri Dec  4 12:06:05 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Tools_ROIWidget(object):
    def setupUi(self, Tools_ROIWidget):
        Tools_ROIWidget.setObjectName("Tools_ROIWidget")
        Tools_ROIWidget.resize(230, 157)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Tools_ROIWidget.sizePolicy().hasHeightForWidth())
        Tools_ROIWidget.setSizePolicy(sizePolicy)
        self.verticalLayout_3 = QtGui.QVBoxLayout(Tools_ROIWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(Tools_ROIWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horAddILROIBtn = QtGui.QPushButton(self.groupBox)
        self.horAddILROIBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.horAddILROIBtn.setObjectName("horAddILROIBtn")
        self.horizontalLayout_3.addWidget(self.horAddILROIBtn)
        self.horRemILROIBtn = QtGui.QPushButton(self.groupBox)
        self.horRemILROIBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.horRemILROIBtn.setObjectName("horRemILROIBtn")
        self.horizontalLayout_3.addWidget(self.horRemILROIBtn)
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verAddILROIBtn = QtGui.QPushButton(self.groupBox)
        self.verAddILROIBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.verAddILROIBtn.setObjectName("verAddILROIBtn")
        self.horizontalLayout.addWidget(self.verAddILROIBtn)
        self.verRemILROIBtn = QtGui.QPushButton(self.groupBox)
        self.verRemILROIBtn.setMaximumSize(QtCore.QSize(30, 16777215))
        self.verRemILROIBtn.setObjectName("verRemILROIBtn")
        self.horizontalLayout.addWidget(self.verRemILROIBtn)
        spacerItem3 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.addBoxROIBtn = QtGui.QPushButton(self.groupBox)
        self.addBoxROIBtn.setObjectName("addBoxROIBtn")
        self.horizontalLayout_2.addWidget(self.addBoxROIBtn)
        self.remBoxROIBtn = QtGui.QPushButton(self.groupBox)
        self.remBoxROIBtn.setObjectName("remBoxROIBtn")
        self.horizontalLayout_2.addWidget(self.remBoxROIBtn)
        spacerItem5 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox)

        self.retranslateUi(Tools_ROIWidget)
        QtCore.QMetaObject.connectSlotsByName(Tools_ROIWidget)

    def retranslateUi(self, Tools_ROIWidget):
        Tools_ROIWidget.setWindowTitle(QtGui.QApplication.translate("Tools_ROIWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Tools_ROIWidget", "Region of interest", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.horAddILROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.horRemILROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Tools_ROIWidget", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.verAddILROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.verRemILROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.addBoxROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "+ Box", None, QtGui.QApplication.UnicodeUTF8))
        self.remBoxROIBtn.setText(QtGui.QApplication.translate("Tools_ROIWidget", "- Box", None, QtGui.QApplication.UnicodeUTF8))

